### ISSUE TITLE
Path & direct negative cost.

### ISSUE THREAD

**Issue by berktaylan** [guanghechen/algorithm.ts#1]
Hello for the bellman-ford

Is there any plan tu show path-route for each calculation,

As well does it support negative costs ?

**Comment by guanghechen** [comment]
Hi, I don't quite understand your requirement, do you want to get a shortest path from the source point to the given point?

What does `negative cost` mean? If there is a negative cycle in the graph, there is no shortest path.

**Comment by berktaylan** [comment]
Hi and thanks for the reply.

What im trying to do is calculate shortest path from currency conversion rate to all others. For do this i need to add two way rates for each pair and instead of multiplying rates to summarize on bellman for im taking log10 of each of them to able to summarize on bellman ford .
 
Let me give you an example.

Pair A = this is the base pair. And i want to find shortest path from A to each pair.

A - B = 1
B - A = -1

B - C = 0.87
C - B = -0.87

C - D = 5
D - C = -5

My goal is to find shortest path from A to each source ( B , C , D )

**Comment by guanghechen** [comment]
Hi @berktaylan, is the following pseudo code what you want to achieve?

```typescript
getShortestPath(A, A) => [A]
getShortestPath(A, B) => [A, B]
getShortestPath(A, C) => [A, B, C]
getShortestPath(A, D) => [A, B, C, D]
```

I refactor the bellman-ford implementation and I hope it is good enough to meet your needs. Here is an example when you want to obtain the shortestPath of source point to each other points:

```typescript
import bellmanFord from '@algorithm.ts/bellman-ford'

const A = 0
const B = 1
const C = 2
const D = 3

const graph: IGraph = {
  N: 4,
  source: A,
  edges: [
    // Nodes: [A, B, C, D]
    { to: B, cost: 1 },       // A-B (1)
    { to: A, cost: -1 },      // B-A (-1)
    { to: C, cost: 0.87 },    // B-C (0.87)
    { to: B, cost: -0.87 },   // C-B (-0.87)
    { to: D, cost: 5 },       // C-D (5)
    { to: C, cost: -5 },      // D-C (-5)
  ],
  G: [[0], [1, 2], [3, 4], [5]],
}

const noNegativeCycle: boolean = bellmanFord(graph, undefined, context => {
  const a2aPath: number[] = context.getShortestPathTo(A)
  const a2bPath: number[] = context.getShortestPathTo(B)
  const a2cPath: number[] = context.getShortestPathTo(C)
  const a2dPath: number[] = context.getShortestPathTo(D)

  a2aPath // => [0]
  a2bPath // => [0, 1]
  a2cPath // => [0, 1, 2]
  a2dPath // => [0, 1, 2, 3]
})
```

Can you try it with the latest code on the develop branch?https://github.com/guanghechen/algorithm.ts/blob/develop/packages/bellman-ford/README.md#example

**Comment by berktaylan** [comment]
What if i add 

D - B = 1
B - D = -1 

I think that makes a problem but i cant understand.

**Comment by guanghechen** [comment]
Because there is a negative cycle when you add the additional edge `D-B = 1` and `B-D = -1`. A negative cyle is:

````
B --> D: -1
D --> C: -5
C --> B: -0.87
````

And I told you over and over again that if there is a negative cycle in the graph, there will be no shortest path.

**Comment by berktaylan** [comment]
Sorry. But there is no way if there is a negative cycle ? Do you have any suggestion

**Comment by guanghechen** [comment]
I repeat, if there is a negative cycle there will be no shortest path. For example, which path do you think is the shortest path from A to B?

1. `A -> B`, cost: 1
2. `A -> B -> D -> C -> B`, cost: 1 + (-1) + (-5) + (-0.87) = -5.87
3. `A -> B -> D -> C -> B -> D -> C -> B`, cost: 1 + (-1) + (-5) + (-0.87) + (-1) + (-5) + (-0.87) = -12.74
4. ....

**Comment by berktaylan** [comment]
Hi @guanghechen , i do really respect respect your help and explain on this topic :)

> 1. `A -> B`, cost: 1
> 2. `A -> B -> D -> C -> B`, cost: 1 + (-1) + (-5) + (-0.87) = -5.87
> 3. `A -> B -> D -> C -> B -> D -> C -> B`, cost: 1 + (-1) + (-5) + (-0.87) + (-1) + (-5) + (-0.87) = -12.74
> 4. ....

But on step 3, why does it still re-visit ( re-calculate ) B-D  ( at step 5 ), since same way already visited at step 2 ( B-D ), i mean does bellman algo doesnt prevent this ?

**Comment by guanghechen** [comment]
Yes, bellman-ford algo won't prevent it, this algorithm is designed to find the shortest path from source node to other nodes.
The algo relies on slack operations, where each node may be considered multiple times while the algorithm is running, that means it does not guarantee that each node appears only once in the path, and in fact "shortest path" does not require that.

**Comment by berktaylan** [comment]
Thanks for the explain @guanghechen 

Are you able to make some paid work for the script i need, if yes how can i contact you ?

**Comment by guanghechen** [comment]
Sorry, I don't have a lot of free time. If you can describe your requirements more clearly, maybe I can give you some ideas to solve it.

**Comment by berktaylan** [comment]
Thank you.

So my case is calculate shortest path from A currency to all other currencies on exchange market. I plan to have 10.000 different pair , and need to calculate from A to all others fast as possible . ( I think maybe nodejs might be not great for this, but i need to do it with it )

Currency rates are this A/B = 1.37 , B/A = 0.729 ( means 1/ 1.37 )

And currency rate conversion is multiplying,
A/B = 1.37
B/C = 0.7
A-B-C = 1.37*0.7

Since bellman ford need to have summarize the cost of the ways, i get log10 of each pair rate and use them as a weight ( cost )
A/B = 1.37 = log10( 1.37 ) = 0.136
B/A = 0.729 = log10( 0.729 ) = -0.13 ( negative )

So since i need to add reverse rate of each pair as well, one of the ways log makes it negative number;

So my goal is;
Add cost of each pair & reverse cost of it ( A/B = 013 B/A = -0.13 )
There will be negative cycles ( so i think i should prevent double use of same path on each unique calculation
And calculate shortest cost & route of each currency to A 

Thanks

**Comment by guanghechen** [comment]
Hum, an interesting question. 

I was really thinking about this problem and wrote some code to try solving it, but I didn't get a solution, sorry for not helping

**Comment by berktaylan** [comment]
Thanks .

Here is an example at golang, not sure its good or bad, just leaving here if you want to checkout sometime how they tried to solve it.

https://gist.github.com/ewancook/d39a06b2ee6e3f7c7c4d6cb66f2dcff7

**Comment by guanghechen** [comment]
Maybe you can run the Floyd algo to get a cost map, that is, costMap[x][y] represent the mimum cost from x to y.
Then when you want get the shortest path from S-T, you can find a middle point `X0` which satisfied that `costMap[S][X0] + costMap[X0][T]=costMap[S][T]`, then find a point `X1` satisfied that `costMap[S][X1] + costMap[X1][X0]=costMap[S][X0]`.. repeat these process until the `Xk=S`, then you can get a shortest path from S to T: `S -> X_{k-1} -> X_{k-2} -> ... X1 -> X0 -> T`

**Comment by guanghechen** [comment]
> Here is an example at golang, not sure its good or bad, just leaving here if you want to checkout sometime how they tried to solve it.
https://gist.github.com/ewancook/d39a06b2ee6e3f7c7c4d6cb66f2dcff7

Bellman-ford algo can find a negative cycles, but it is hard to find a shortest path without duplicated nodes on the path.

**Comment by berktaylan** [comment]
Still working on it and making some research :)

What if i limit the total route to 3 or 4 , and find the shortest path with cost max 3 or 4 step rule or something. Do you think it can help with bellman ?

Also another thing is each step adds extra fee on my case like %0.01 on both ways, it is something i can use with negative cycles maybe ?

**Comment by guanghechen** [comment]
> Maybe you can run the Floyd algo to get a cost map, that is, costMap[x][y] represent the mimum cost from x to y.
> Then when you want get the shortest path from S-T, you can find a middle point `X0` which satisfied that `costMap[S][X0] + costMap[X0][T]=costMap[S][T]`, then find a point `X1` satisfied that `costMap[S][X1] + costMap[X1][X0]=costMap[S][X0]`.. repeat these process until the `Xk=S`, then you can get a shortest path from S to T: `S -> X_{k-1} -> X_{k-2} -> ... X1 -> X0 -> T`

Can you try this algo? I think it can find an approximate optimal solution.
